"""add ultimo_aceite to Professional

Revision ID: 016241b96bb2
Revises: cddaaf8edb3d
Create Date: 2025-04-19 21:33:31.970027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '016241b96bb2'
down_revision: Union[str, None] = 'cddaaf8edb3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professionals', sa.Column('ultimo_aceite', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professionals', 'ultimo_aceite')
    # ### end Alembic commands ###
