"""add rating to professionals and price to service_requests

Revision ID: 85f61616dd24
Revises: 02123fe5e0c0
Create Date: 2025-04-19 16:13:46.443414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85f61616dd24'
down_revision: Union[str, None] = '02123fe5e0c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professionals', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professionals', 'rating')
    # ### end Alembic commands ###
