"""add total_atendimentos to Professional

Revision ID: cddaaf8edb3d
Revises: 85f61616dd24
Create Date: 2025-04-19 21:31:22.194057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cddaaf8edb3d'
down_revision: Union[str, None] = '85f61616dd24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professionals', sa.Column('total_atendimentos', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professionals', 'total_atendimentos')
    # ### end Alembic commands ###
